package huper.digital.iam.service;

import huper.digital.iam.dto.ChangePasswordRequest;
import huper.digital.iam.dto.GroupDTO;
import huper.digital.iam.dto.UserCreateRequest;
import huper.digital.iam.dto.UserDTO;
import huper.digital.iam.dto.UserInviteRequest;
import huper.digital.iam.exception.AuthenticationException;
import huper.digital.iam.entity.AuthGroupEntity;
import huper.digital.iam.entity.AuthOrganizationEntity;
import huper.digital.iam.entity.AuthUserEntity;
import huper.digital.iam.entity.AuthUserOrganizationEntity;
import huper.digital.iam.entity.AuthUserOrganizationId;
import huper.digital.iam.exception.UserAlreadyExistsException;
import huper.digital.iam.repository.AuthGroupRepository;
import huper.digital.iam.repository.AuthOrganizationRepository;
import huper.digital.iam.repository.AuthUserRepository;
import huper.digital.iam.security.JwtTokenService;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.NotFoundException;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@ApplicationScoped
@Slf4j
public class UserService {

  @Inject
  AuthUserRepository userRepository;

  @Inject
  AuthGroupRepository groupRepository;

  @Inject
  AuthOrganizationRepository organizationRepository;

  @Inject
  GroupService groupService;

  @Inject
  JwtTokenService jwtTokenService;

  @Inject
  PermissionService permissionService;

  public List<UserDTO> findAll(Integer first, Integer max, String search) {
    try {
      int safeFirst = first == null ? 0 : Math.max(0, first);
      int safeMax = max == null ? 100 : Math.max(1, max);
      
      log.info("Buscando usuários - first: {}, max: {}, search: '{}'", safeFirst, safeMax, search);
      
      List<AuthUserEntity> entities;
      if (StringUtils.isBlank(search)) {
        entities = userRepository.findAll().list();
        log.info("Total de usuários no banco (sem filtro): {}", entities.size());
      } else {
        entities = userRepository.find(
            "LOWER(email) LIKE ?1 OR LOWER(firstName) LIKE ?1 OR LOWER(lastName) LIKE ?1",
            "%" + search.toLowerCase() + "%"
        ).list();
        log.info("Total de usuários encontrados com filtro '{}': {}", search, entities.size());
      }
      
      // Apply pagination
      List<AuthUserEntity> paginatedEntities;
      if (entities.isEmpty() || safeFirst >= entities.size()) {
        paginatedEntities = List.of();
        log.info("Nenhum usuário para retornar após paginação");
      } else {
        int endIndex = Math.min(safeFirst + safeMax, entities.size());
        paginatedEntities = entities.subList(safeFirst, endIndex);
        log.info("Aplicando paginação - retornando {} de {} usuários", paginatedEntities.size(), entities.size());
      }
      
      List<UserDTO> users = paginatedEntities.stream()
          .map(this::toDto)
          .toList();

      log.info("Listados {} usuários (DTOs)", users.size());
      return users;
    } catch (Exception e) {
      log.error("Erro ao listar usuários: {}", e.getMessage(), e);
      throw new RuntimeException("Falha ao listar usuários", e);
    }
  }

  public List<UserDTO> findAll() {
    return findAll(0, 1000, null);
  }

  public UserDTO findById(String userId) {
    Long id = Long.parseLong(userId);
    return userRepository.findByIdOptional(id)
        .map(this::toDto)
        .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));
  }

  public Optional<UserDTO> findByEmail(String email) {
    return userRepository.findByEmail(email).map(this::toDto);
  }

  @Transactional
  public UserDTO create(UserCreateRequest request) {
    try {
      if (userRepository.findByEmail(request.email()).isPresent()) {
        throw new UserAlreadyExistsException("Já existe um usuário com o email: " + request.email());
      }

      // Create user entity
      AuthUserEntity entity = new AuthUserEntity();
      // ID will be auto-generated by Hibernate
      entity.setEmail(request.email());
      entity.setPhone(request.phone());
      entity.setFirstName(request.firstName());
      entity.setLastName(request.lastName());
      entity.setBirthDate(request.birthDate());
      entity.setTaxIdentifier(request.taxIdentifier());
      entity.setAddress(request.address());
      entity.setPasswordHash(jwtTokenService.hashPassword(request.password()));
      entity.setEnabled(Boolean.TRUE);
      entity.setStatus("ATIVO"); // Set status as active for regular creation

      userRepository.persist(entity);
      log.info("Usuário criado com sucesso: {}", request.email());

      // Create organization with user's name
      String organizationName = StringUtils.isNotBlank(request.firstName()) 
          ? request.firstName() 
          : (StringUtils.isNotBlank(request.email()) ? request.email().split("@")[0] : "Organização " + entity.getId());
      
      AuthOrganizationEntity organization = new AuthOrganizationEntity();
      organization.setName(organizationName);
      organization.setIsActive(true);
      organizationRepository.persist(organization);
      log.info("Organização criada com sucesso: {}", organizationName);

      // Associate user as owner of the organization
      AuthUserOrganizationEntity userOrganization = new AuthUserOrganizationEntity();
      AuthUserOrganizationId userOrgId = new AuthUserOrganizationId(entity.getId(), organization.getId());
      userOrganization.setId(userOrgId);
      userOrganization.setUser(entity);
      userOrganization.setOrganization(organization);
      userOrganization.setOwner(true);
      entity.getOrganizationMemberships().add(userOrganization);
      userRepository.persist(entity);
      log.info("Usuário {} associado como owner da organização {}", entity.getId(), organization.getId());

      // Create or find "Administradores" group with all roles
      String adminGroupName = "Administradores";
      Optional<GroupDTO> existingGroup = groupService.findByName(adminGroupName);
      AuthGroupEntity adminGroup;
      
      if (existingGroup.isPresent()) {
        adminGroup = groupRepository.findByIdOptional(existingGroup.get().id())
            .orElseThrow(() -> new RuntimeException("Grupo Administradores não encontrado"));
        log.info("Grupo Administradores já existe, usando grupo existente");
      } else {
        // Get all role constants from database
        List<String> allRoles = permissionService.getAllPermissions();
        
        adminGroup = new AuthGroupEntity();
        adminGroup.setName(adminGroupName);
        adminGroup.setOrganization(organization);
        adminGroup.getRoleNames().addAll(allRoles);
        groupRepository.persist(adminGroup);
        log.info("Grupo Administradores criado com {} roles", allRoles.size());
      }

      // Associate user to the Administradores group
      entity.getGroups().add(adminGroup);
      userRepository.persist(entity);
      log.info("Usuário {} associado ao grupo Administradores", entity.getId());

      return toDto(entity);

    } catch (Exception e) {
      log.error("Erro ao criar usuário {}: {}", request.email(), e.getMessage(), e);
      throw e;
    }
  }


  @Transactional
  public UserDTO update(String userId, UserDTO userDTO) {
    try {
      Long id = Long.parseLong(userId);
      AuthUserEntity entity = userRepository.findByIdOptional(id)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));

      if (StringUtils.isNotBlank(userDTO.email())
          && !entity.getEmail().equalsIgnoreCase(userDTO.email())) {
        var userWithSameEmail = userRepository.findByEmail(userDTO.email());
        if (userWithSameEmail.isPresent() && !userWithSameEmail.get().getId().equals(id)) {
          throw new UserAlreadyExistsException("Já existe outro usuário com o email: " + userDTO.email());
        }
      }

      if (StringUtils.isNotBlank(userDTO.email())) {
        entity.setEmail(userDTO.email());
      }
      entity.setPhone(userDTO.phone());
      entity.setFirstName(userDTO.firstName());
      entity.setLastName(userDTO.lastName());
      entity.setTaxIdentifier(userDTO.taxIdentifier());
      entity.setAddress(userDTO.address());
      if (userDTO.enabled() != null) {
        entity.setEnabled(userDTO.enabled());
      }

      userRepository.persist(entity);
      log.info("Usuário atualizado com sucesso: {}", userId);
      return toDto(entity);

    } catch (Exception e) {
      log.error("Erro ao atualizar usuário {}: {}", userId, e.getMessage(), e);
      throw new RuntimeException("Falha ao atualizar usuário", e);
    }
  }

  @Transactional
  public void delete(String userId) {
    try {
      Long id = Long.parseLong(userId);
      AuthUserEntity entity = userRepository.findByIdOptional(id)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));
      userRepository.delete(entity);
      log.info("Usuário removido com sucesso: {}", userId);

    } catch (Exception e) {
      log.error("Erro ao remover usuário {}: {}", userId, e.getMessage(), e);
      throw new RuntimeException("Falha ao remover usuário", e);
    }
  }

  public List<GroupDTO> getUserGroups(String userId) {
    try {
      Long id = Long.parseLong(userId);
      AuthUserEntity user = userRepository.findByIdOptional(id)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));

      List<GroupDTO> groups = user.getGroups().stream()
          .map(g -> new GroupDTO(
              g.getId(),
              g.getName(),
              g.getOrganization() != null ? g.getOrganization().getId() : null,
              g.getIsDefault(),
              g.getRoleNames().stream().toList(),
              null
          ))
          .toList();

      log.debug("Listados {} grupos do usuário {}", groups.size(), userId);
      return groups;

    } catch (Exception e) {
      log.error("Erro ao listar grupos do usuário {}: {}", userId, e.getMessage(), e);
      throw new RuntimeException("Falha ao listar grupos do usuário", e);
    }
  }

  @Transactional
  public void addToGroup(Long userId, Long groupId) {
    try {
      AuthUserEntity user = userRepository.findByIdOptional(userId)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));
      AuthGroupEntity group = groupRepository.findByIdOptional(groupId)
          .orElseThrow(() -> new NotFoundException("Grupo não encontrado: " + groupId));

      user.getGroups().add(group);
      userRepository.persist(user);
      log.info("Usuário {} adicionado ao grupo {}", userId, groupId);

    } catch (Exception e) {
      log.error("Erro ao adicionar usuário {} ao grupo {}: {}", userId, groupId, e.getMessage(), e);
      throw new RuntimeException("Falha ao adicionar usuário ao grupo", e);
    }
  }

  @Transactional
  public void removeFromGroup(Long userId, Long groupId) {
    try {
      AuthUserEntity user = userRepository.findByIdOptional(userId)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));
      AuthGroupEntity group = groupRepository.findByIdOptional(groupId)
          .orElseThrow(() -> new NotFoundException("Grupo não encontrado: " + groupId));

      user.getGroups().remove(group);
      userRepository.persist(user);
      log.info("Usuário {} removido do grupo {}", userId, groupId);

    } catch (Exception e) {
      log.error("Erro ao remover usuário {} do grupo {}: {}", userId, groupId, e.getMessage(), e);
      throw new RuntimeException("Falha ao remover usuário do grupo", e);
    }
  }

  @Transactional
  public void changePassword(String userId, ChangePasswordRequest request) {
    try {
      Long id = Long.parseLong(userId);
      AuthUserEntity user = userRepository.findByIdOptional(id)
          .orElseThrow(() -> new NotFoundException("Usuário não encontrado: " + userId));

      if (!jwtTokenService.matchesPassword(request.currentPassword(), user.getPasswordHash())) {
        throw new AuthenticationException("Senha atual incorreta");
      }

      user.setPasswordHash(jwtTokenService.hashPassword(request.newPassword()));
      userRepository.persist(user);
      log.info("Senha alterada com sucesso para o usuário: {}", userId);

    } catch (Exception e) {
      log.error("Erro ao alterar senha do usuário {}: {}", userId, e.getMessage(), e);
      throw e;
    }
  }

  @Transactional
  public void inviteUser(UserInviteRequest request) {
    try {
      // Validate that at least email or phone is provided
      if (StringUtils.isBlank(request.email()) && StringUtils.isBlank(request.phone())) {
        throw new IllegalArgumentException("Email ou telefone deve ser fornecido");
      }

      // Check if user already exists by email
      if (StringUtils.isNotBlank(request.email()) && userRepository.findByEmail(request.email()).isPresent()) {
        throw new UserAlreadyExistsException("Já existe um usuário com o email: " + request.email());
      }

      // Generate a secure temporary password for the invitation
      // User will need to set their own password on first login
      String temporaryPassword = UUID.randomUUID().toString().substring(0, 12);

      // Create user entity
      AuthUserEntity entity = new AuthUserEntity();
      // ID will be auto-generated by Hibernate (BIGSERIAL)
      
      // Email is required in the entity, so if not provided, generate a temporary one
      if (StringUtils.isNotBlank(request.email())) {
        entity.setEmail(request.email());
      } else if (StringUtils.isNotBlank(request.phone())) {
        // Generate a temporary email based on phone number
        String tempEmail = "temp_" + request.phone().replaceAll("[^0-9]", "") + "@invite.temp";
        entity.setEmail(tempEmail);
        log.info("Email temporário gerado para convite via telefone: {}", tempEmail);
      } else {
        throw new IllegalArgumentException("Email ou telefone deve ser fornecido");
      }
      
      if (StringUtils.isNotBlank(request.phone())) {
        entity.setPhone(request.phone());
      }
      entity.setFirstName(request.firstName());
      entity.setLastName(request.lastName());
      entity.setPasswordHash(jwtTokenService.hashPassword(temporaryPassword));
      entity.setEnabled(Boolean.TRUE); // User is enabled but needs to change password
      entity.setStatus("CONVIDADO"); // Set status as invited

      userRepository.persist(entity);
      log.info("Usuário convidado criado: email={}, phone={}, id={}", request.email(), request.phone(), entity.getId());

      // Associate with organization if provided
      if (StringUtils.isNotBlank(request.organizationId())) {
        try {
          Long orgId = Long.parseLong(request.organizationId());
          AuthOrganizationEntity organization = organizationRepository.findByIdOptional(orgId)
              .orElseThrow(() -> new NotFoundException("Organização não encontrada: " + request.organizationId()));

          AuthUserOrganizationEntity userOrganization = new AuthUserOrganizationEntity();
          AuthUserOrganizationId userOrgId = new AuthUserOrganizationId(entity.getId(), organization.getId());
          userOrganization.setId(userOrgId);
          userOrganization.setUser(entity);
          userOrganization.setOrganization(organization);
          userOrganization.setOwner(false); // Invited users are not owners
          entity.getOrganizationMemberships().add(userOrganization);
          log.info("Usuário associado à organização: {}", organization.getName());
        } catch (NumberFormatException e) {
          log.warn("ID de organização inválido: {}", request.organizationId());
          throw new IllegalArgumentException("ID de organização inválido: " + request.organizationId());
        }
      }

      // Associate with groups if provided
      if (request.groupIds() != null && !request.groupIds().isEmpty()) {
        for (String groupIdStr : request.groupIds()) {
          try {
            Long groupId = Long.parseLong(groupIdStr);
            AuthGroupEntity group = groupRepository.findByIdOptional(groupId)
                .orElseThrow(() -> new NotFoundException("Grupo não encontrado: " + groupIdStr));
            entity.getGroups().add(group);
            log.info("Usuário associado ao grupo: {}", group.getName());
          } catch (NumberFormatException e) {
            log.warn("ID de grupo inválido: {}", groupIdStr);
          } catch (NotFoundException e) {
            log.warn("Grupo {} não encontrado, ignorando associação", groupIdStr);
          }
        }
      }

      userRepository.persist(entity);
      
      // TODO: Send invitation email/SMS with temporary password and link to set password
      // For now, we log the temporary password (in production, this should be sent via email/SMS)
      log.info("Convite criado para usuário ID: {} - Email: {} - Phone: {} - Senha temporária: {}", 
          entity.getId(), request.email(), request.phone(), temporaryPassword);
      
    } catch (Exception e) {
      log.error("Erro ao enviar convite para email={}, phone={}: {}", request.email(), request.phone(), e.getMessage(), e);
      throw e;
    }
  }

  private UserDTO toDto(AuthUserEntity user) {
    List<String> groupIds = user.getGroups() == null
        ? List.of()
        : user.getGroups().stream().map(AuthGroupEntity::getId).map(String::valueOf).toList();

    java.util.Set<String> roleNames = new java.util.HashSet<>();

    // Include group roles as "realmRoles" as well, to keep @RolesAllowed compatible.
    if (user.getGroups() != null) {
      user.getGroups().forEach(g -> {
        if (g.getRoleNames() != null) {
          g.getRoleNames().stream()
              .filter(n -> n != null && !n.isBlank())
              .forEach(roleNames::add);
        }
      });
    }

    return new UserDTO(
        user.getId(),
        user.getEmail(),
        user.getPhone(),
        user.getFirstName(),
        user.getLastName(),
        user.getBirthDate(),
        user.getTaxIdentifier(),
        user.getAddress(),
        user.getEnabled(),
        user.getStatus(),
        groupIds,
        roleNames.stream().toList()
    );
  }
}

